package dao;

import entity.ViewTest;
import entity.ViewTestExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ViewTestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table viewtest
     *
     * @mbg.generated Sun Sep 16 23:01:54 CST 2018
     */
    long countByExample(ViewTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table viewtest
     *
     * @mbg.generated Sun Sep 16 23:01:54 CST 2018
     */
    int deleteByExample(ViewTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table viewtest
     *
     * @mbg.generated Sun Sep 16 23:01:54 CST 2018
     */
    int insert(ViewTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table viewtest
     *
     * @mbg.generated Sun Sep 16 23:01:54 CST 2018
     */
    int insertSelective(ViewTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table viewtest
     *
     * @mbg.generated Sun Sep 16 23:01:54 CST 2018
     */
    List<ViewTest> selectByExample(ViewTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table viewtest
     *
     * @mbg.generated Sun Sep 16 23:01:54 CST 2018
     */
    int updateByExampleSelective(@Param("record") ViewTest record, @Param("example") ViewTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table viewtest
     *
     * @mbg.generated Sun Sep 16 23:01:54 CST 2018
     */
    int updateByExample(@Param("record") ViewTest record, @Param("example") ViewTestExample example);
}