package entity;

public class Category {
    private String belong;

    @Override
    public String toString() {
        return "Category{" +
                "belong='" + belong + '\'' +
                ", id=" + id +
                ", parentId=" + parentId +
                ", name='" + name + '\'' +
                ", cDesc='" + cDesc + '\'' +
                ", level=" + level +
                '}';
    }

    public String getBelong() {
        return belong;
    }

    public void setBelong(String belong) {
        this.belong = belong;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_category.id
     *
     * @mbg.generated Sat Sep 15 22:10:57 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_category.parent_id
     *
     * @mbg.generated Sat Sep 15 22:10:57 CST 2018
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_category.name
     *
     * @mbg.generated Sat Sep 15 22:10:57 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_category.c_desc
     *
     * @mbg.generated Sat Sep 15 22:10:57 CST 2018
     */
    private String cDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_category.level
     *
     * @mbg.generated Sat Sep 15 22:10:57 CST 2018
     */
    private Integer level;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_category.id
     *
     * @return the value of t_category.id
     *
     * @mbg.generated Sat Sep 15 22:10:57 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_category.id
     *
     * @param id the value for t_category.id
     *
     * @mbg.generated Sat Sep 15 22:10:57 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_category.parent_id
     *
     * @return the value of t_category.parent_id
     *
     * @mbg.generated Sat Sep 15 22:10:57 CST 2018
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_category.parent_id
     *
     * @param parentId the value for t_category.parent_id
     *
     * @mbg.generated Sat Sep 15 22:10:57 CST 2018
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_category.name
     *
     * @return the value of t_category.name
     *
     * @mbg.generated Sat Sep 15 22:10:57 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_category.name
     *
     * @param name the value for t_category.name
     *
     * @mbg.generated Sat Sep 15 22:10:57 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_category.c_desc
     *
     * @return the value of t_category.c_desc
     *
     * @mbg.generated Sat Sep 15 22:10:57 CST 2018
     */
    public String getcDesc() {
        return cDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_category.c_desc
     *
     * @param cDesc the value for t_category.c_desc
     *
     * @mbg.generated Sat Sep 15 22:10:57 CST 2018
     */
    public void setcDesc(String cDesc) {
        this.cDesc = cDesc == null ? null : cDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_category.level
     *
     * @return the value of t_category.level
     *
     * @mbg.generated Sat Sep 15 22:10:57 CST 2018
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_category.level
     *
     * @param level the value for t_category.level
     *
     * @mbg.generated Sat Sep 15 22:10:57 CST 2018
     */
    public void setLevel(Integer level) {
        this.level = level;
    }
}