package entity;

public class ViewTest {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column viewtest.id
     *
     * @mbg.generated Sun Sep 16 23:01:54 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column viewtest.parent_id
     *
     * @mbg.generated Sun Sep 16 23:01:54 CST 2018
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column viewtest.name
     *
     * @mbg.generated Sun Sep 16 23:01:54 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column viewtest.c_desc
     *
     * @mbg.generated Sun Sep 16 23:01:54 CST 2018
     */
    private String cDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column viewtest.level
     *
     * @mbg.generated Sun Sep 16 23:01:54 CST 2018
     */
    private Integer level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column viewtest.belong
     *
     * @mbg.generated Sun Sep 16 23:01:54 CST 2018
     */
    private String belong;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column viewtest.id
     *
     * @return the value of viewtest.id
     *
     * @mbg.generated Sun Sep 16 23:01:54 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column viewtest.id
     *
     * @param id the value for viewtest.id
     *
     * @mbg.generated Sun Sep 16 23:01:54 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column viewtest.parent_id
     *
     * @return the value of viewtest.parent_id
     *
     * @mbg.generated Sun Sep 16 23:01:54 CST 2018
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column viewtest.parent_id
     *
     * @param parentId the value for viewtest.parent_id
     *
     * @mbg.generated Sun Sep 16 23:01:54 CST 2018
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column viewtest.name
     *
     * @return the value of viewtest.name
     *
     * @mbg.generated Sun Sep 16 23:01:54 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column viewtest.name
     *
     * @param name the value for viewtest.name
     *
     * @mbg.generated Sun Sep 16 23:01:54 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column viewtest.c_desc
     *
     * @return the value of viewtest.c_desc
     *
     * @mbg.generated Sun Sep 16 23:01:54 CST 2018
     */
    public String getcDesc() {
        return cDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column viewtest.c_desc
     *
     * @param cDesc the value for viewtest.c_desc
     *
     * @mbg.generated Sun Sep 16 23:01:54 CST 2018
     */
    public void setcDesc(String cDesc) {
        this.cDesc = cDesc == null ? null : cDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column viewtest.level
     *
     * @return the value of viewtest.level
     *
     * @mbg.generated Sun Sep 16 23:01:54 CST 2018
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column viewtest.level
     *
     * @param level the value for viewtest.level
     *
     * @mbg.generated Sun Sep 16 23:01:54 CST 2018
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column viewtest.belong
     *
     * @return the value of viewtest.belong
     *
     * @mbg.generated Sun Sep 16 23:01:54 CST 2018
     */
    public String getBelong() {
        return belong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column viewtest.belong
     *
     * @param belong the value for viewtest.belong
     *
     * @mbg.generated Sun Sep 16 23:01:54 CST 2018
     */
    public void setBelong(String belong) {
        this.belong = belong == null ? null : belong.trim();
    }
}